CREATE TABLE Addresse(
    AID     NUMBER CONSTRAINT PK_Addresse PRIMARY KEY,
    PLZ     NUMBER,
    ORT     VARCHAR2(100),
    STRASSE VARCHAR2(100)
);

CREATE TABLE ANGEBOT(
    PERSID NUMBER CONSTRAINT PK_ANGEBOT PRIMARY KEY
);

CREATE TABLE BESUCH(
    BID      NUMBER CONSTRAINT PK_BESUCH PRIMARY KEY,
    DATUMVON DATE,
    DATUMBIS DATE
);

CREATE TABLE FACH(
    FID         NUMBER CONSTRAINT PK_FACH PRIMARY KEY,
    BEZEICHNUNG VARCHAR2(100)
);

CREATE TABLE GEMEINDE(
    GID            NUMBER CONSTRAINT PK_GEMEINDE PRIMARY KEY,
    GEMBEZEICHNUNG VARCHAR2(100)
);

CREATE TABLE GRUNDSTEUERART(
    GSAID       NUMBER CONSTRAINT PK_GRUNDSTEUERART PRIMARY KEY,
    BEZEICHNUNG VARCHAR2(100)
);

CREATE TABLE GRUNDSTUECK(
    GRUNDSTUECKNR  NUMBER CONSTRAINT PK_GRUNDSTUECK PRIMARY KEY,
    EINHEITSWERT   NUMBER,
    FLAECHE        NUMBER,
    STEUERMESSZAHL NUMBER
);

CREATE TABLE HEBESATZ(
    GSAID     NUMBER,
    GUELTIGAB DATE,
    SATZ      NUMBER,
    CONSTRAINT PK_HEBESATZ PRIMARY KEY (GSAID, GUELTIGAB)
);

CREATE TABLE KATASTRALGEMEINDE(
    KGID        NUMBER CONSTRAINT PK_KATASTRALGEMEINDE PRIMARY KEY,
    BEZEICHNUNG VARCHAR2(100)
);

CREATE TABLE KIGAKIND(
    PERSID           NUMBER CONSTRAINT PK_KIGAKIND PRIMARY KEY,
    GEBURTSTAGSDATUM DATE,
    ERMAESSIGUNGPROZ NUMBER
);

CREATE TABLE KIGAMITARBEITERIN(
    PERSID NUMBER,
    KID    NUMBER,
    CONSTRAINT PK_KIGAMITARBEITERIN PRIMARY KEY (PERSID, KID)
);

CREATE TABLE KIGAZEITFENSTER(
    KID NUMBER CONSTRAINT PK_KIGAZEITFENSTER PRIMARY KEY
);

CREATE TABLE KINDERGARTEN(
    KID NUMBER CONSTRAINT PK_KINDERGARTEN PRIMARY KEY
);

CREATE TABLE LIEGENSCHAFT(
	EZ NUMBER CONSTRAINT PK_LIEGENSCHAFT PRIMARY KEY, --IDK MUSS SPAETER NOCH ANGEPASST WERDEN
);

CREATE TABLE MSERVICEFUERLIEGENSCHAFT(
	MID NUMBER CONSTRAINT PK_MSERVICEFUERLIEGENSCHAFT PRIMARY KEY, --FK MUSS GECHANGED WERDEN
	DATUMVON DATE,
	DATUMBIS DATE,
);

CREATE TABLE MUELLGEBUEHR(
	MID NUMBER CONSTRAINT PK_MUELLGEBUEHR PRIMARY KEY
);

CREATE TABLE MUELLSERVICE(
	MID NUMBER CONSTRAINT PK_MUELLSERVICE PRIMARY KEY,
	BEZEICHNUNG VARCHAR2(200),
);

CREATE TABLE MUSIKLEHRER(
	PERSID NUMBER CONSTRAINT PK_MUSIKLEHRER PRIMARY KEY,
	EINSTELLUNGSDATUM DATE
);

CREATE TABLE MUSIKSCHUELER(
	PERSID NUMBER CONSTRAINT PK_MUSIKSCHUELER PRIMARY KEY,
	GEBURTSTAGSDATUM DATE,
	TELEFONNUMMER NUMBER
);

CREATE TABLE ORT(
	OID NUMBER CONSTRAINT PK_ORT PRIMARY KEY,
	ORTBEZEICHNUNG VARCHAR2(200),
);

CREATE TABLE PERSON(
	PERSID NUMBER CONSTRAINT PK_PERSON PRIMARY KEY,
	NACHNAME VARCHAR2(200),
	VORNAME VARCHAR2(200),
	GESCHLECHT VARCHAR2(100),
);

--CREATE TABLE PLZSTRASSE

CREATE TABLE POSTLEITZAHL(
	PLZ NUMBER CONSTRAINT PK_POSTLEITZAHL PRIMARY KEY
);

CREATE TABLE SEMESTER(
	SID NUMBER CONSTRAINT PK_SEMESTER PRIMARY KEY,
	BEGINDATUM DATE,
	ENDDATUM DATE,
	SEMESTER VARCHAR2(100),
	SCHULJAHR VARCHAR2(100)
);

CREATE TABLE STRASSE(
	STID NUMBER CONSTRAINT PK_STRASSE PRIMARY KEY,
	STRASSENNAME VARCHAR2(100)
);

CREATE TABLE TITEL(
	TITELID NUMBER CONSTRAINT PK_TITEL PRIMARY KEY,
	BEZEICHNUNG VARCHAR2(200)
);

CREATE TABLE UNTERRICHT(
	UID NUMBER CONSTRAINT PK_UNTERRICHT PRIMARY KEY,
	--REST NOCH MACHEN
);

CREATE TABLE UNTERRICHTSART(
	UAID NUMBER CONSTRAINT PK_UNTERRICHTSART PRIMARY KEY,
	BEZEICHNUNG VARCHAR2(200),
	DAUER VARCHAR2(100),
	SEMBEITRAG NUMBER
);

CREATE TABLE VORSCHREIBUNG(
	VID NUMBER CONSTRAINT PK_VORSCHREIBUNG PRIMARY KEY,
	BETRAG NUMBER,
	AUSSTELLUNGSDATUM DATE,
	FAELLIGKEITSDATUM DATE,
	BANKEINZUG VARCHAR2(200)
	--REST NOCH MACHEN
);

CREATE TABLE VORSCHREIBUNGSART(
	VAID NUMBER CONSTRAINT PK_VORSCHREIBUNGSART PRIMARY KEY,
	BEZEICHNUNG VARCHAR2(200)
);

CREATE TABLE ZAHLUNGSEINGANG(
	ZEID NUMBER CONSTRAINT PK_ZAHLUNGSEINGANG PRIMARY KEY,
	EINGANGSDATUM DATE,
	BETRAG NUMBER,
	KUNDENDATEN VARCHAR2(200),
	IBAN VARCHAR2(200),
	BIC VARCHAR2(200),
);

CREATE TABLE ZAHLUNGSPFLICHTIGER(
	PERSID NUMBER CONSTRAINT PK_ZAHLUNGSPFLICHTIG PRIMARY KEY,
	STEUERNUMMER NUMBER,
	IBAN VARCHAR2(200),
	BIC VARCHAR2(200)
);

CREATE TABLE ZEITFENSTER(
	ZFID NUMBER CONSTRAINT PK_ZEITFENSTER PRIMARY KEY,
	BEZEICHNUNG VARCHAR2(200),
	ZEITVON VARCHAR2(80),
	ZEITBIS VARCHAR2(80),
	GEBUEHRGEMEINDE NUMBER,
	GEBUEHRAUSWERTIGE NUMBER
);