-- CREATE_ALL.sql Script

CREATE TABLE Addresse(
	AID	NUMBER	CONSTRAINT PK_Addresse PRIMARY KEY,
	PLZ	NUMBER,
	ORT	VARCHAR,
	STRASSE	VARCHAR,
);

CREATE TABLE ANGEBOT(
	PERSID	NUMBER	CONSTRAINT PK_ANGEBOT PRIMARY KEY,
);

CREATE TABLE BESUCH(
	BID	NUMBER	CONSTRAINT PK_BESUCH PRIMARY KEY,
	DATUMVON	DATE,
	DATUMBIS	DATE,
);

CREATE TABLE FACH(
	FID	 NUMBER	CONSTRAINT PK_FACH PRIMARY KEY,
	BEZEICHNUNG	VARCHAR,
);

CREATE TABLE GEMEINDE(
	GID	NUMBER CONSTRAINT PK_GEMEINDE PRIMARY KEY,
	GEMBEZEICHNUNG	VARCHAR,
);

CREATE TABLE GRUNDSTEUERART(
	GSAID	NUMBER	CONSTRAINT PK_GRUNDSTEUERART PRIMARY KEY,
	BEZEICHNUNG	VARCHAR,
);

CREATE TABLE GRUNDSTUECK(
	GRUNDSTUECKNR	NUMBER	CONSTRAINT PK_GRUNDSTUECK PRIMARY KEY,
	EINHEITSWERT	NUMBER,
	FLAECHE	NUMBER,
	STEUERMESSZAHL	NUMBER,
);

CREATE TABLE HEBESATZ(
	GSAID	NUMBER CONSTRAINT PK_HEBESATZ PRIMARY KEY,
	GUELTIGAB	DATE,
	SATZ	VARCHAR,
);

CREATE TABLE KATASTRALGEMEINDE(
	KGID	NUMBER	CONSTRAINT PK_KATASTRALGEMEINDE PRIMARY KEY,
	BEZEICHNUNG VARCHAR,
);

CREATE TABLE KIGAKIND(
	PERSID	NUMBER	CONSTRAINT PK_KIGAKIND PRIMARY KEY,
	GEBURTSTAGSDATUM	DATE,
	ERMAESSIGUNGPROZ	NUMBER
);

CREATE TABLE KIGAMITARBEITERIN(
	PERSID	NUMBER	CONSTRAINT PK_KIGAMITARBEITERIN PRIMARY KEY,
	KID	NUMBER	CONSTRAINT PK_KIGAMITARBEITERIN PRIMARY KEY,
);

CREATE TABLE KIGAZEITFENSTER(
	KID	NUMBER	CONSTRAINT PK_KIGAZEITFENSTER PRIMARY KEY,
);

CREATE TABLE KINDERGARTEN(
	KID	NUMBER	
);
